[package]
name = "vdb"
version = "0.1.0"
authors = ["James"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.4.0"
rand = "0.7.3"
#reqwest = { version = "0.10", features = ["blocking", "json"] }